name: Deploy Package

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Pull Source Files
      uses: actions/checkout@v1

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Run a multi-line script
      shell: pwsh
      run: |
        Get-Content -path content\q-sys-plugin-template.qplug
        
