name: Deploy Package

on:
  push:
    branches:
      -master
    tags:
      - '*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Pull Source Files
      uses: actions/checkout@v1

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Update version in .qplug file
      run: |
        $TAG = $Env:GITHUB_REF.Replace("refs/tags/","")
        # Will get exactly the first instance of a .qplug file
        $QPLUG = (Get-ChildItem -Path "content" -Include *.qplug -Force -Recurse -File | Select-Object -First 1).Name
        ((Get-Content -path content\$QPLUG -Raw) -replace '0.0.0-localdev',$TAG) | Set-Content content\$QPLUG
        Get-Content -path content\$QPLUG -Raw
  
    - name: Pack with nuget.exe
      run: |
        nuget pack
        dir
        
