name: Deploy Package

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Pull Source Files
      uses: actions/checkout@v1

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Get Tag (Should be present)
      shell: pwsh
      run: |
        echo $GITHUB_REF
      
    - name: Update version in .qplug file
      shell: pwsh
      run: |
        (Get-Content -path content\q-sys-plugin-template.qplug -Raw) -replace '0.0.0-localdev','1.0.0'
        
    - name: Output .qplug file
      shell: pwsh
      run: |
        Get-Content -path content\q-sys-plugin-template.qplug -Raw
        
